export const USER_NAME = 'USER_NAME'
export const USER_ACCOUNT_TYPE = 'USER_ACCOUNT_TYPE'
export const USER_BALANCE = 'USER_BALANCE'
export const USER_TOKEN = 'USER_TOKEN'
export const USER_WALLET = 'USER_WALLET'
export const DISPLAY_STATE = 'DISPLAY_STATE';